#!/usr/bin/env python3
"""Regenerate ALERT-AUDIT.md from a real audit run.

The document was hand-assembled around `monitor.py --audit` output the first
time, and that is a drift hazard: the prose said "13 lines audited, 2
unreconciled" while the file it described had been regenerated. A document that
states a verdict about another file has to be produced by re-deriving that
verdict, not by someone remembering it.

So this runs the audit, parses its output, and writes the document. It exits
non-zero when any line fails to reconcile, which makes it usable as a gate
rather than only as a report.

Usage:
    uv run tools/alert_audit_doc.py
    uv run tools/alert_audit_doc.py --check    # verify without writing
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
TASK = REPO / "task1-spend-observability"
MONITOR = TASK / "monitor.py"
DEFAULT_RAW = TASK / "data" / "raw_samples.jsonl"
DEFAULT_ALERTS = TASK / "alerts.jsonl"
OUT = TASK / "ALERT-AUDIT.md"

PREAMBLE = """# Alert audit

Every line in `alerts.jsonl` re-derived from the raw window that produced it.
The rule is re-run at the instant the line was written and **every evidence field
it produced is compared**; fields the alerter contributes, sustain, materiality
bands, are checked against the alerter's own invariants.

Where a top-up, package reset or reverted blip sits anywhere in the estimation
window, the incident is recomputed **with that event undone**. An alert that
disappears when the event is removed was caused by normal operations, and the
task text is explicit that a balance being topped up is normal operations and
not an incident. A note recording that an event happened nearby is not proof of
anything.

The audit is side-effect free: it replays into a temporary database and a
temporary alert path, and hashes the audited file before and after to prove it.

```
python3 monitor.py --audit --raw data/raw_samples.jsonl
```

It exits non-zero if any line fails to reconcile. This document is generated by
`uv run tools/alert_audit_doc.py`, which runs that audit and fails the same way,
so the document cannot claim a verdict the audit did not produce.
"""


def headline(row: dict) -> str:
    """The one number a reader would quote for this line."""
    ev = row.get("evidence") or {}
    if isinstance(ev.get("runway_h"), (int, float)):
        return f"{ev['runway_h']:.1f} h"
    # burn_anomaly measures a deviation in units of the estimator's own scale,
    # which is a MAD. Reporting the raw burn instead would put a credits/h and a
    # USD/h in the same column and invite the comparison the dashboard refuses
    # to make elsewhere.
    if isinstance(ev.get("deviation_in_scale_units"), (int, float)):
        return f"{ev['deviation_in_scale_units']:.1f} MAD"
    if isinstance(ev.get("stale_s"), (int, float)):
        return f"{ev['stale_s']:.1f} s"
    return ""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--raw", default=str(DEFAULT_RAW))
    ap.add_argument("--alerts", default=str(DEFAULT_ALERTS))
    ap.add_argument("--check", action="store_true",
                    help="run the audit and report, write nothing")
    args = ap.parse_args()

    proc = subprocess.run(
        [sys.executable, str(MONITOR), "--audit",
         "--raw", args.raw, "--alerts", args.alerts],
        capture_output=True, text=True)
    audit = (proc.stdout or "") + (proc.stderr or "")
    # A generated document must be deterministic given the same inputs, or it
    # churns on every run and produces diffs that say nothing. Two things in the
    # audit output are not: how long the replay took, and where the raw log
    # lives on the machine that ran it. Neither is evidence about the alerts.
    audit = re.sub(r"(\[replay\] \d+ records) in [\d.]+s from \S+",
                   r"\1 from the raw window", audit)

    m = re.search(r"unreconciled lines:\s*(\d+) of (\d+)", audit)
    if not m:
        print("could not find the audit verdict in its own output", file=sys.stderr)
        print(audit[-2000:], file=sys.stderr)
        return 2
    unreconciled, audited = int(m.group(1)), int(m.group(2))

    # Counterfactual failures are the ones the task text makes a blocker: an
    # alert that exists only because a balance was topped up is reporting normal
    # operations as an incident.
    topup_only = len(re.findall(r"caused solely by a top_up", audit))
    blip_only = len(re.findall(r"caused solely by a reverted_blip", audit))

    rows = [json.loads(line) for line in
            Path(args.alerts).read_text(encoding="utf-8").splitlines() if line.strip()]
    bad = {int(n) for n in re.findall(r"^\[(\d+)\][^\[]*?UNRECONCILED",
                                      audit, re.M | re.S)}
    records = sum(1 for _ in Path(args.raw).open(encoding="utf-8"))
    # Stamp the DATA, not the repository. This document is a claim about
    # alerts.jsonl against the raw records, and the repo HEAD is no part of that
    # claim: in a tree several sessions are committing to, HEAD moves every few
    # minutes, so a regeneration that changed nothing but the stamp dirtied the
    # file and made "final gates on a clean tree" unachievable by construction.
    # The raw digest changes exactly when the subject of the audit changes.
    raw_digest = hashlib.sha256(Path(args.raw).read_bytes()).hexdigest()[:16]

    body = [PREAMBLE, "", "| provenance | |", "|---|---|",
            f"| alert lines audited | {audited} |",
            f"| unreconciled | **{unreconciled}** |",
            f"| caused solely by a top-up | **{topup_only}** |",
            f"| caused solely by a reverted blip | **{blip_only}** |",
            f"| raw records | {records:,} |",
            f"| raw log sha256 | `{raw_digest}` |",
            "| regenerate | `uv run tools/alert_audit_doc.py` |",
            "", "## Every line", "",
            "| # | when | rule | provider | headline | reconciled |",
            "|---:|---|---|---|---:|---|"]
    for i, row in enumerate(rows, 1):
        ok = "**no**" if i in bad else "yes"
        body.append(f"| {i} | {row['ts']} | `{row.get('rule', '')}` | "
                    f"`{row.get('provider', '')}` | {headline(row)} | {ok} |")

    body += ["", "## State of this audit", ""]
    if unreconciled == 0 and topup_only == 0 and blip_only == 0:
        body += [
            f"**Every one of the {audited} lines reconciles.** Each rule was re-run at "
            "the instant its line was written, every evidence field compared, and "
            "each incident recomputed with any nearby top-up, package reset or "
            "reverted blip undone. No line survives only because of one of those "
            "events, which is the property the task text requires: a balance being "
            "topped up is normal operations, not an incident.",
            "",
            "This was not always true. An earlier build shipped a "
            "`package_exhaustion` line for `bounceban` that disappeared when "
            "either a +3 credit reverted blip or a +3 credit top-up was removed "
            "from its estimation window: a 180 hour projection that a 0.04% "
            "perturbation of the balance could flip. The uncertainty guard, which "
            "requires a projection to survive its own burn estimate recomputed one "
            "MAD slower, is what removed it. The audit is what found it.",
        ]
    else:
        body += [
            f"**This audit fails: {unreconciled} of {audited} lines do not "
            f"reconcile**, {topup_only} caused solely by a top-up and {blip_only} "
            "solely by a reverted blip. The failing lines are marked in the table "
            "above and detailed below. A failing audit is published rather than "
            "hidden, because the alternative is a document that agrees with itself "
            "and not with the data.",
        ]

    body += ["", "## Full reconciliation output", "", "```", audit.strip(), "```", ""]
    text = "\n".join(body)

    verdict = (f"audited {audited}, unreconciled {unreconciled}, "
               f"top-up-only {topup_only}, blip-only {blip_only}")
    if args.check:
        print(f"CHECK: {verdict}")
    elif OUT.exists() and OUT.read_text(encoding="utf-8") == text:
        # Writing identical bytes still updates mtime and, in some tooling,
        # still reads as a change. If the audit says the same thing, say nothing.
        print(f"unchanged {OUT.relative_to(REPO)}: {verdict}")
    else:
        OUT.write_text(text, encoding="utf-8")
        print(f"wrote {OUT.relative_to(REPO)}: {verdict}")
    return 1 if (unreconciled or topup_only or blip_only) else 0


if __name__ == "__main__":
    raise SystemExit(main())
